config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations"}
  # devise_for :users

  devise_scope :user do
      get "/signin", to: "devise/sessions#new", as: "sign_in"
      delete "/sign_out", to: "devise/sessions#destroy", as: "sign_out"
      get "sign_up", to: "devise/registrations#new", as: "sign_up"
  end

  root 'wineries#home'

  post "/wineries_search", to: "wineries#search", as: :winery_search
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase
  resources :users do
    resources :profiles
  end

  resources :wineries do
    resources :reviews
  end

  resources :users do
    resources :memories
  end

  resources :wineries do
    resources :memories
    resources :memory_details
  end

  resources :wineries do
    resources :memories do
      resources :memory_details
    end
  end


  resources :memories do
    resources :memory_details
  end

  resources :profiles
  resources :wineries
  resources :memories
  resources :reviews
  resources :memory_details

  resources :fb_sessions, only: [:create, :destroy]




  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/memory_detail.rb
# == Schema Information
#
# Table name: memory_details
#
#  id           :integer          not null, primary key
#  notes        :string
#  visited      :boolean
#  visited_date :date
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  winery_id    :integer
#  memory_id    :integer
#

class MemoryDetail < ActiveRecord::Base
	has_one :winery
	belongs_to :memory

	validates_presence_of :memory_id, :winery_id
end

app/controllers/memory_details_controller.rb
class MemoryDetailsController < ApplicationController
	before_action :authenticate_user!

	def index
      @memory_details = MemoryDetail.all
  end

	def new 
      @memory_detail = MemoryDetail.new

      if params[:winery]
        @winery = Winery.find(params[:winery]) 
# this is correct param when coming from winery/index
      else
        @winery = Winery.find(params[:winery_id])
# error when coming from new memory creation
      end 
	end

  def create
    @memory_detail = MemoryDetail.new(memory_detail_params)
    
    if @memory_detail.save
      redirect_to memory_path(@memory_detail.memory_id), notice: "Your Memory was updated successfully"
    else
      render "new"
    end
  end

	def edit
		@memory_detail = get_memory_detail
	end

  def update
    @memory_detail = get_memory_detail
    if @memory_detail.update_attributes(memory_detail_params) 
      redirect_to memory_path(@memory_detail.memory), notice: "Your Memory was updated successfully"
    else
      render 'edit'
    end
  end

  # def select
  #   @memory_detail = MemoryDetail.new
  #   if current_user
  #     @winery = Winery.find(params[:winery])
  #   end
  # end
 	
 	def show
    
 		@memory_detail = get_memory_detail
  end

	def destroy
    @memory_detail = get_memory_detail
    @memory_detail.destroy
    redirect_to memory_path, notice: "Item successfully deleted from this Memory"
  end
  
  private

  def memory_detail_params
  	params.require(:memory_detail).permit(:notes, :visited, :visited_date, :winery_id, :memory_id)
  end

  def get_memory_detail
  	MemoryDetail.find(params[:id])
  end
end

app/helpers/memory_details_helper.rb
module MemoryDetailsHelper
end

app/views/memory_details/edit.html.erb
<div class="container">
		<div class="row">
			<div class="col-md-8"> 
				<center><h1>Edit Memory for <%=@memory_detail.memory.name %></h1>
				<br>for<br><br>
				<h3><b> <%= Winery.where(id: @memory_detail[:winery_id]).first
.name %></h3></b></center><br>
					<p>Update any fields you want to edit:</p>

					<%= simple_form_for @memory_detail do |f| %>

						<%= f.input :notes, label: "What I want to remember about this winery..." %>
						<%= f.input :visited, label: "I have visited this winery before " %>
						
						<%= f.input :visited_date, placeholder: "Date", as: :date_picker, placeholder: "MM/DD/YYYY", wrapper: :ranged_datetime, label: "Trip Date" %>
						<!-- make visited date appear if above is selected -->
						<%= f.hidden_field :winery_id, value: @memory_detail[:winery_id] %>
						<%= f.submit "Yay!"%>

					<% end %>
				</div>
			</div>
		</div>

	<p><%= javascript_include_tag "application" %> </p>

app/views/memory_details/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-8"> 
			
			<h1>Don't forget about <i><%= @winery.name %></i>!</h1>
<!-- @winery.try(:name) -->
			<%= simple_form_for @memory_detail do |f| %>
				<%= f.association :memory, collection: Memory.all.where(user_id: current_user), label: "Add to my Memory for: " %>
				<%= f.input :notes, label: "What I want to remember about this winery..." %>
				<%= f.input :visited, label: "I have visited this winery before " %>
				<%= f.input :visited_date, placeholder: "Visit Date", as: :date_picker, placeholder: "MM/DD/YYYY", wrapper: :ranged_datetime, label: "Trip Date" %>
				<br><br>
				<!-- make visited date appear if above is selected -->
				<%= f.hidden_field :winery_id, value: @winery.id %>
				<%= f.submit "Yay!"%>

			<% end %>

				<br><center>or <br>
				<h3><%= link_to "Create a New Memory", new_winery_memory_path(@winery) %> </h3></center> 

			<br><br>
		</div>
	</div>
</div>
<p><%= javascript_include_tag "application" %> </p>

<!-- visited date is not passing -->