config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations"}
  # devise_for :users

  devise_scope :user do
      get "/signin", to: "devise/sessions#new", as: "sign_in"
      delete "/sign_out", to: "devise/sessions#destroy", as: "sign_out"
      get "sign_up", to: "devise/registrations#new", as: "sign_up"
  end

  root 'wineries#home'

  post "/wineries_search", to: "wineries#search", as: :winery_search
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase
  resources :users do
    resources :profiles
  end

  resources :wineries do
    resources :reviews
  end

  resources :users do
    resources :memories
  end

  resources :wineries do
    resources :memories
    resources :memory_details
  end

  resources :wineries do
    resources :memories do
      resources :memory_details
    end
  end


  resources :memories do
    resources :memory_details
  end

  resources :profiles
  resources :wineries
  resources :memories
  resources :reviews
  resources :memory_details

  resources :fb_sessions, only: [:create, :destroy]




  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/memory.rb
# == Schema Information
#
# Table name: memories
#
#  id            :integer          not null, primary key
#  name          :string
#  trip_date     :date
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  user_id       :integer
#  trip_date_end :date
#

class Memory < ActiveRecord::Base
	belongs_to :user
	has_many :memory_details, dependent: :destroy
	

	validates_presence_of :name, :user_id
end

app/controllers/memories_controller.rb
class MemoriesController < ApplicationController
  before_action :authenticate_user!

	def index

    if current_user
      @memories = Memory.where(user_id: current_user.id)
    else
      @memories = Memory.all
    end 
  end

	def new
    
      @memory = Memory.new
      @winery = Winery.where(id: params[:winery_id]).first
	end

  def create

    @memory = Memory.new(memory_params)
    @winery = Winery.where(id: params[:memory][:winery_id]).first

    if @memory.save
      redirect_to new_winery_memory_memory_detail_path(@winery, @memory), notice: "Your New Memory was created successfully"
    else
      render "new"
    end
  end

	def edit
		@memory = get_memory
	end

  def update
    @memory = get_memory
    if @memory.update_attributes(memory_params) 
      redirect_to memory_path(@memory), notice: "Your Memory was updated successfully"
    else
      render 'edit'
    end
  end

  # def select
  #   @memory = Memory.new
  #   if current_user
  #     @memories = Memory.where(user_id: current_user)
  #     @winery = Winery.find(params[:winery])
  #   end
  # end
 	
 	def show
    
 		@memory = get_memory
    # @memory_details = MemoryDetail.where(memory_id: @memory)
    # @winery = Winery.where(id: @memory)
  end

	def destroy
    @memory = get_memory
    @memory.destroy
    redirect_to memories_path, notice: "Memory successfully deleted"
  end
  
  private

  def memory_params
  	params.require(:memory).permit(:user_id, :name, :trip_date, :trip_date_end)
  end

  def get_memory
  	Memory.find(params[:id])
  end
end

app/helpers/memories_helper.rb
module MemoriesHelper
end

app/views/memories/edit.html.erb
<div class="container">
		<div class="row">
			<div class="col-md-8"> 
				<h1>Edit My Memory </h1>
					<p>Update any fields you want to edit:</p>

					<%= simple_form_for @memory, html: {class: 'form-horizontal'}  do |f| %>

						<%= f.input :name, label: "Memory for: " %>
						<div class='row datetimerange'>
							<%= f.input :trip_date, placeholder: "Start", as: :date_picker, wrapper: :ranged_datetime, label: "Trip Start Date" %>
							<%= f.input :trip_date_end, placeholder: "End", as: :date_picker, wrapper: :ranged_datetime, label: "Trip End Date" %>
						</div>
						<%= f.hidden_field :user_id, value: @memory.user_id %>
						<%= f.hidden_field :winery_id, value: @winery.id unless @winery.nil? %>
						<%= f.submit "Update My Memory"%>	

					<% end %>
				</div>
			</div>
		</div>

	<p><%= javascript_include_tag "application" %> </p>

app/views/memories/index.html.erb
<h1 style="color:#000000;">My Memories</h1>
<p>
	<table class="table table-striped table-hover">
		<tr class="small">
					<th></th>
					<th style="width:10%">Name </th>
					<th style="width:20%">Trip Dates </th>
					<th></th>
					<th style="width:100%">Details </th>
				</tr>
			<% @memories.each do |memory| %>
			
				<tr>
				 <td style="width:10%"><%= link_to "#{memory.name}", memory_path(memory) %></td>
				 <td style="width:20%">
				 	<% if memory.trip_date != nil %>
				 		<%= memory.trip_date.strftime("%B %e %Y") %> 
				 		<%= " to " + memory.trip_date_end.strftime("%B %e %Y") unless memory.trip_date_end.nil? %>
				 		<% end %>
				 	</td>
				 	<td>
				 		<!-- insert memory_details -->
				 	</td>
				<td><%= link_to "Edit Memory", edit_memory_path(memory), class: 'btn btn-info' %>
				</td>
			
			<% end %>
	</table>
</p>
<p><%= javascript_include_tag "application" %> </p>

app/views/memories/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-8"> 
			
			<h1>Let's get started building a new Memory! </h1>

			<%= simple_form_for @memory, html: {class: 'form-horizontal'} do |f| %>
				<%= f.input :name, label: "Memory for: " %>
				<div class='row datetimerange'>
					<%= f.input :trip_date, placeholder: "Start", as: :date_picker, wrapper: :ranged_datetime, label: "Trip Start Date" %>
						<%= f.input :trip_date_end, placeholder: "End", as: :date_picker, wrapper: :ranged_datetime, label: "Trip End Date" %>
				</div>
				<%= f.hidden_field :user_id, value: current_user.id %>
				<%= f.hidden_field :winery_id, value: @winery.id %>
				<%= f.submit "Create a Memory"%>

			<% end %>
			<br><br>
		</div>
	</div>
</div>
<p><%= javascript_include_tag "application" %> </p>

app/views/memories/show.html.erb
<p><%= javascript_include_tag "application" %> </p>
<h1 style="color:#000000;"><%= @memory.name %></h1>
<p>
	<table class="table table-striped table-hover">
		
			<tr class="small">
						<td style="width:20%"><ul>
							<% if @memory.trip_date != nil %>
				 		<%= @memory.trip_date.strftime("%B %e %Y") %> 
				 		<%= " to " + @memory.trip_date_end.strftime("%B %e %Y") unless @memory.trip_date_end.nil? %>
				 		<% end %>
						 	</ul>
						</td>
			</tr>
			<tr>
				<th>Winery </th>
				<th>Notes </th>
				<th></th>
				<th>Date of Visit</th>
			</tr>
				<% @memory.memory_details.each do |detail| %>
					<tr class="small">
						<td><ul>
							<b><%= link_to Winery.where(id: detail.winery_id).first.name, winery_path(detail.winery_id) %></b>
							</ul>
						</td>
						<td><%= detail.notes %>
						</td>
						<td><% if detail.visited == true %>
									I've been here before
							<% end %>
						</td>
						<td>
							<%= detail.visited_date.strftime("%B %e %Y") unless detail.visited_date.nil?%>
							
						</td>
						<td><%= link_to "Edit Memory Detail", edit_memory_detail_path(detail), class: 'btn btn-info' %>
				</td>
						<% end %>
			</tr>	
	</table>
</p>