config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations"}
  # devise_for :users

  devise_scope :user do
      get "/signin", to: "devise/sessions#new", as: "sign_in"
      delete "/sign_out", to: "devise/sessions#destroy", as: "sign_out"
      get "sign_up", to: "devise/registrations#new", as: "sign_up"
  end

  root 'wineries#home'

  post "/wineries_search", to: "wineries#search", as: :winery_search
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase
  resources :users do
    resources :profiles
  end

  resources :wineries do
    resources :reviews
  end

  resources :users do
    resources :memories
  end

  resources :wineries do
    resources :memories
    resources :memory_details
  end

  resources :wineries do
    resources :memories do
      resources :memory_details
    end
  end


  resources :memories do
    resources :memory_details
  end

  resources :profiles
  resources :wineries
  resources :memories
  resources :reviews
  resources :memory_details

  resources :fb_sessions, only: [:create, :destroy]




  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/winery.rb
# == Schema Information
#
# Table name: wineries
#
#  id          :integer          not null, primary key
#  name        :string
#  bio         :text
#  street      :string
#  city        :string
#  state       :string
#  zip         :integer
#  photo       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  phone       :string
#  email       :string
#  appointment :boolean
#  pets        :boolean
#  picnic      :boolean
#  fee         :float
#  open        :time
#  close       :time
#  website     :string
#

class Winery < ActiveRecord::Base
	has_many :reviews, dependent: :destroy
	belongs_to :memory_details

	validates_presence_of :name

	# before_create for search entry
	# scope :sonoma, -> {where(city: "Sonoma")}
	# downcase all db entries
	scope :city, -> (city){where(city: city)}
end

app/controllers/wineries_controller.rb
class WineriesController < ApplicationController

	def index

      @wineries = Winery.all
  end

	def new
      @winery = Winery.new
	end

  def create
    @winery = Winery.new(winery_params)
  end

	def edit
		@winery = get_winery
	end

  def update
    @winery = get_winery
    if @winery.update_attributes(winery_params)
      redirect_to wineries_path(@winery, notice: "Winery updated successfully")
    else
      render 'edit'
    end
  end

 	def show
 		@winery = get_winery
    if current_user
      @existing_review = @winery.reviews.exists?(:user_id => current_user.id)
    else
      @existing_review = false
    end
    # @friends_review = @winery.reviews.exists?(:user_id => current_user.id)
  end

  def search
  	# @search_address = Winery.find_by_address(params["SearchInput"])
  	# add this method or figure out how to search
    # downcase after entry

    # currently restricted to search by city but need to make by address
    if !params[:city].blank?
      @city = params[:city]
      @wineries = Winery.city(@city)
      render 'search'
    else
      @wineries = Winery.all
      render 'index'
    end
  end

	def destroy
    @winery = get_winery
    @winery.destroy
    redirect_to wineries_path, notice: "Winery successfully deleted"
  end

  private

  def winery_params
  	params.require(:winery).permit(:name, :bio, :street, :city, :state, :zip, :photo, :phone, :email, :appointment, :pets, :picnic, :fee, :open, :close, :website)
  end

  def get_winery
  	Winery.find(params[:id])
  end
end

app/helpers/wineries_helper.rb
module WineriesHelper
end

app/views/wineries/_friends_reviews.html.erb
<h4><b><center>Reviews by Your Friends</center></b></h4><br><br>
<!-- need to connect via omni auth for friend associations -->
				<table>
					<% if current_user %>
						<% @winery.reviews.each do |review| %>
						<% if review.user_id != current_user.id %>
					<tr class="small">
						<td><ul>
							<b><%= review.user.profile.first_name + " " + review.user.profile.last_name + "'s Review:" %></b>&emsp; <%= review.comment %>
							</ul>
						</td>
						<% end %>
						<% end %>
					</tr>
					<% end %>
				</table>

app/views/wineries/_has_review.html.erb
<h4><center>Your Reviews  </center></h4>
<br>
					<table>
						<tr>
							<th style="width:30%"><center>Created Date </center></th>
							<th style="width:50%"><center>Rating </center></th>
							<th style="width:100%"><center>Comments </center></th>
						</tr>
						<% @winery.reviews.each do |review| %>
						<% if review.user_id == current_user.id %>
					<tr align="center">
						<td style="width:30%">
							<%= review.created_at.strftime("%B %e %Y") %></td>
							<td style="width:50%"><%= review.rating.to_s + " Stars" %></td>
							<td style="width:100%"><%= review.comment %></td>
							
						</td>
					</tr>
						<% end %>
					<% end %>
				</table>
		<br>
<center><%= link_to "Add Another Review", new_winery_review_path(@winery), class: 'btn btn-primary' %></center>

app/views/wineries/_no_review.html.erb
<h1><center>Have you been here?  <%= link_to "Add Your Review", new_winery_review_path(@winery), class: 'btn btn-primary' %></center></h1>

app/views/wineries/home.html.erb
<body >
  <h1><center>Welcome to the Ultimate Wine Country Trip Planner</center></h1>

<div class="col-md-12">
	<div class="table-responsive" align="center">


    <h1 style="color:#000000;"><i>We are here to help you Create Memories</i></h1>
    <br><%= image_tag('WineGlasses.jpg', size: '100') %>
		<p><br>Where do you want to find tasting rooms?
      <br><br>

      <%= form_tag("wineries_search", method: "post") do %>
        <%= label_tag(:city, "Search by city:") %>
        <%= text_field_tag(:city) %>
        <%= submit_tag("Go", class: "btn btn-lg btn-default") %>
      <% end %>
    </p>					
    <br>
    <a href=<%= wineries_path %>>View All Wineries</a>
		<p><%= javascript_include_tag "application" %> </p>

  </div>

</div>
</body>

app/views/wineries/index.html.erb
<body>

<h1 style="color:#000000;">All wineries in Sonoma County</h1>
<p>
	<table class="table table-striped table-hover">

			<% @wineries.each do |winery| %>
			<tr class="small">
						<td style="width:5%"><%= link_to image_tag('wine-glass-icon.jpg', size: '30x59'), new_memory_detail_path(winery:winery) %>
						</td>
						<!-- <td> for a fb like button
							<div
							  class="fb-like"
							  data-share="true"
							  data-width="450"
							  data-show-faces="true">
							</div>
						</td> -->
						<td style="width:20%"><ul><%= image_tag(winery.photo, size: "100x50", :class => 'img-rounded img-responsive') unless winery.photo.nil? %>
						 </td>
						 <td><%= link_to "#{winery.name}", winery_path(winery) %><br>
						 	<%= winery.street %><br>
						 	<%= winery.city + ", " + winery.state + " " + winery.zip.to_s %><br>
						 	<%= winery.phone[0...3] +"."+ winery.phone[3...6]+ "."+ winery.phone[6...10] %></ul>
						</td>
			</tr>
			<% end %>
	</table>
</p>
<p><%= javascript_include_tag "application" %> </p>
</body>

app/views/wineries/search.html.erb
<body>
<h1 style="color:#000000;">All wineries in the city of <%= @city %></h1>
<p>
	<table class="table table-striped table-hover">
		
			<% @wineries.each do |winery| %>
			<tr class="small">
						<td style="width:5%"><%= link_to image_tag('wine-glass-icon.jpg', size: '30x59'), new_memory_detail_path(winery:winery) %>
						</td>
						<!-- <td> for a fb like button
							<div
							  class="fb-like"
							  data-share="true"
							  data-width="450"
							  data-show-faces="true">
							</div>
						</td> -->
						<td style="width:20%"><ul><%= image_tag(winery.photo, size: "100x50", :class => 'img-rounded img-responsive') unless winery.photo.nil? %>
						 </td>
						 <td><%= link_to "#{winery.name}", winery_path(winery) %><br>
						 	<%= winery.street %><br>
						 	<%= winery.city + ", " + winery.state + " " + winery.zip.to_s %><br>
						 	<%= winery.phone[0...3] +"."+ winery.phone[3...6]+ "."+ winery.phone[6...10] %></ul>
						</td>
			</tr>
			<% end %>
	</table>
</p>
<p><%= javascript_include_tag "application" %> </p>
</body>

app/views/wineries/show.html.erb
<p><%= javascript_include_tag "application" %> </p>
<h1 style="color:#000000;"><%= @winery.name %></h1>
<p>
	<table class="table table-striped table-hover">
		
			<tr class="small">
						<td style="width:5%"><%= link_to image_tag('wine-glass-icon.jpg', size: '30x59'), new_memory_detail_path(winery:params[:id]) %>
						</td><td style="width:20%"><ul><%= image_tag(@winery.photo, size: "100x50", :class => 'img-rounded img-responsive') unless @winery.photo.nil? %>
						 </td>
						 <td style="width:30%"><%= @winery.street %><br>
						 	<%= @winery.city + ", " + @winery.state + " " + @winery.zip.to_s %><br>
						 	</ul>
						</td>
						<td>
							<% if @existing_review %>
								<%= render 'wineries/has_review' %>
							<% else %>
								<%= render 'wineries/no_review' %>
							<% end %>
						</td>
			</tr>
	</table>
</p>

<p>

	<table class="table table-striped table-hover">
		
			<tr class="small">
				<td style="width:50%"><ul>
					<b>About the Winery: </b><%= @winery.bio %><br><br>
					<b>Contact Info: </b>
					<% if @winery.phone == nil %>
						No phone number
					<% else %>
						<%= @winery.phone[0...3] +"."+ @winery.phone[3...6]+ "."+ @winery.phone[6...10] %>
					<% end %>
					<br>
					<% if @winery.email != nil %>
						<%= "              " + @winery.email %><br><%= @winery.website %>
					<% end %>
					<br><br>
					<b>Tasting Room Hours: </b>
					<% if (@winery.open || @winery.close) == nil %>
						Call for Hours
					<% else %>
						<%= @winery.open.strftime("%I:%M %p") + " to " + @winery.close.strftime("%I:%M %p") %>
					<% end %>
					<br>
					<% if @winery.appointment == true %>
						<%= "     By Appointment Only" %><br>
					<% end %>
					<br>
					<b>Tasting Room Fee: </b><%= "$" + number_with_precision(@winery.fee, :precision => 2) %><br><br>
					<b>Good to Know: </b><br>
					<%= "     Pets Allowed: " + @winery.pets.to_s %><br>
					<%= "     Picnic Area: " + @winery.picnic.to_s %><br>
				</td>
				<td>
					
					<%= render "wineries/friends_reviews" %>
				</td>
			</tr>	
	</table>
</p>




    