config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations"}
  # devise_for :users

  devise_scope :user do
      get "/signin", to: "devise/sessions#new", as: "sign_in"
      delete "/sign_out", to: "devise/sessions#destroy", as: "sign_out"
      get "sign_up", to: "devise/registrations#new", as: "sign_up"
  end

  root 'wineries#home'

  post "/wineries_search", to: "wineries#search", as: :winery_search
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase
  resources :users do
    resources :profiles
  end

  resources :wineries do
    resources :reviews
  end

  resources :users do
    resources :memories
  end

  resources :wineries do
    resources :memories
    resources :memory_details
  end

  resources :wineries do
    resources :memories do
      resources :memory_details
    end
  end


  resources :memories do
    resources :memory_details
  end

  resources :profiles
  resources :wineries
  resources :memories
  resources :reviews
  resources :memory_details

  resources :fb_sessions, only: [:create, :destroy]




  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_auth_stuff.html.erb
<div class="container-fluid" align="right">
   <!-- if on login page, don't show -->


  <% if current_user %>
      <font color="white"><span class="glyphicon glyphicon-user"></span><%= "User: " + current_user.email %></font>
      <br><%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
    <% else %>
      <%= link_to "Sign In", new_user_session_path %>
      |   <%= link_to "Sign Up", new_user_registration_path %>
  <% end %>


 </div>

app/views/layouts/_guest_nav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    
    <ul class="nav navbar-nav">
      <li><%= image_tag('WineGlasses.jpg', size: '50') %></li>
      <li><a href=<%= wineries_path %>>Wineries</a></li>
      <%= form_tag("wineries_search", method: "post", class: "navbar-form navbar-left") do %>
        <font color="grey"><%= label_tag(:city, "Search by city:") %></font>
        <%= text_field_tag(:city) %>
        <%= submit_tag("Go", class: "btn btn-default") %>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <ul class="nav navbar-nav navbar-right">
        <li> <%= render 'layouts/auth_stuff' %> </li>
      </ul>
    </ul>
    
  </div>
 </nav>

app/views/layouts/_main_nav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    
    <ul class="nav navbar-nav">
      <li><%= image_tag('WineGlasses.jpg', size: '50') %></li>
      <li><a href=<%= wineries_path %>>Wineries</a></li>
      
      <%= form_tag("wineries_search", method: "post", class: "navbar-form navbar-left") do %>
        <font color="grey"><%= label_tag(:city, "Search by city:") %></font>
        <%= text_field_tag(:city) %>
        <%= submit_tag("Go", class: "btn btn-default") %>
      <% end %>

    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle">My Stuff <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li>
            <% if current_user.profile != nil %>
              <a href=<%= user_profiles_path(current_user.id) %>>My Profile</a>
            <% else %>
              <a href=<%= new_user_profile_path(current_user.id) %>>Create Profile</a>
            <% end %>
          </li>
          <li><a href=<%= user_memories_path(current_user.id) %>>My Memories</a></li>
          <li><a href=<%= reviews_path %>>My Reviews</a></li>
          <!-- <li role="separator" class="divider"></li>
          <li><a href="#">Separated link</a></li>
          <li role="separator" class="divider"></li>
          <li><a href="#">One more separated link</a></li> -->
        </ul>
      </li>
      <ul class="nav navbar-nav navbar-right">
        <li> <%= render 'layouts/auth_stuff' %> </li>
      </ul>
    </ul>
    
  </div>
 </nav>
 <p>
 <% if notice %>
    <p class="notice"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert"><%= alert %></p>
   <% end %>
 </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WineFinder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js' %>
  

  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container-fluid">
		<p>
      <% if user_signed_in? %>
        <%= render 'layouts/main_nav' %>
      <% else %>
      	<%= render 'layouts/guest_nav' %>
      <% end %>
		</p>
		<%= yield %>
	</div>
</body>
</html>